# Generated by Django 5.1.2 on 2024-10-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('griffin', '0002_project_created_at_project_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='projects/files/'),
        ),
    ]
