# Generated by Django 5.1.2 on 2024-10-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_userproject_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
