# Generated by Django 5.1.2 on 2024-10-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_userproject_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
