# Generated by Django 5.1.2 on 2024-10-10 15:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_userproject_completed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='completed_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
