# Generated by Django 5.1.2 on 2024-10-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_profile_birth_date_remove_profile_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('on-hold', 'On Hold')], default='ongoing', max_length=20),
        ),
    ]
